theme = "native"

[[block]]
block = "disk_space"
path = "/home"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = "/home {available}"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"

[[block]]
block = "sound"
on_click = "pavucontrol -t 3"

[[block]]
block = "time"
interval = 5
format = "%m/%d %R %a"

