name: Update inputs
on:
  schedule:
    # rebuild at 23:11 on Friday
    - cron:  '11 23 * * 5'
  workflow_dispatch:
jobs:
  update_nix_inputs:
    uses: slaier/reusable-workflows/.github/workflows/update_nix_inputs.yml@main
    secrets:
      TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}

